---
name: Scheduled update branch

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'
    #   - cron: "0 1 * * *"

jobs:
    branch:
        runs-on: ubuntu-latest
        steps:
            - uses: peterjgrainger/action-create-branch@v2.0.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
              with:
                  branch: ${{ secrets.UPDATE_BRANCH }}
