---
name: Quality Assurance
on:
    push: 
        branches:
            - ${{ secrets.UPDATE_BRANCH }}
    pull_request: 
        branches:
            - ${{ secrets.UPDATE_BRANCH }}

jobs:
    build:
        name: '[Build/test] Node.js ${{ matrix.nodejs }}'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodejs: [ '10', '12', '14' ]
        steps: 
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.nodejs }}
            - run: npm install
            - run: npm test
