---
name: Automatic update merge

on:
    push:
        branches:
            - testmerge
  # workflow_run:
  #     workflows:
  #         - Auto-commit updates
  #     types:
  #         - completed
  #     branches:
  #         - auto-update

jobs:
    test: 
        steps:
            - name: Test the change
              runs: echo "Something"

  # automerge:
  #   if: github.event.review.state == 'approved' || !github.event.review
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: reitermarkus/automerge@v1
  #       with:
  #         token: ${{ secrets.MY_GITHUB_TOKEN }}
  #         merge-method: rebase
  #         do-not-merge-labels: never-merge
  #         required-labels: automerge
  #         pull-request: ${{ github.event.inputs.pull-request }}
  #         dry-run: true